services:
  mongo-ce:
    image: mongo
    container_name: formio-mongo-ce
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"

  formio-ce:
    image: formio/formio:rc
    container_name: formio-ce
    restart: always
    ports:
      - "3001:3001"
    environment:
      DEBUG: formio:*
      ROOT_EMAIL: admin@example.com
      ROOT_PASSWORD: CHANGEME

      ROOT_URL: http://localhost:3001
      API_URL: http://localhost:3001

      NODE_CONFIG: |
        {
          "mongo": "mongodb://mongo-ce:27017/formio-ce",
          "port": 3001,
          "jwt": {
            "secret": "CHANGEME"
          }
        }

    depends_on:
      - mongo-ce

